version: "3"
services:
  # Database service (pre-built image)
  db:
    container_name: lafabrika-database
    image: lafabrika/database:0.0.1
    volumes:
      - "./pg-data:/var/lib/postgresql/data"
    restart: always
    networks:
      - internal

  # Authentication service
  authentication:
    build: services/authentication
    env_file:
      - ./environment/common.env
    volumes:
      - ./services/authentication:/app
      - ./models/objection:/app/../../models/objection
    ports:
      - "3001:3000"
    networks:
      - internal
    depends_on:
      - db

  # Users service
  users:
    build: services/users
    env_file:
      - ./environment/common.env
    volumes:
      - ./services/users:/app
      - ./models/objection:/app/../../models/objection
    ports:
      - "3002:3000"
    networks:
      - internal
    depends_on:
      - db

  # Accountability service
  accountability:
    build: services/accountability
    env_file:
      - ./environment/common.env
    volumes:
      - ./services/accountability:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
networks:
  internal:
    external: true
