version: "3"
services:
  # Database service (pre-built image)
  db:
    image: lafabrika/database:0.0.1
    restart: always
  # Accountability service
  accountability:
    build: services/accountability
    volumes:
      - ./services/accountability:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
  # Migrations service
  migrations:
    build: services/migrations
    # TTY true will keep the container alive to run migrations
    tty: true
    volumes:
      - ./services/migrations:/migrations
    depends_on:
      - db
