-- Deploy lafabrika:appschema to pg

BEGIN;

CREATE SCHEMA lafabrika AUTHORIZATION lafabrika;

ALTER DEFAULT PRIVILEGES IN SCHEMA lafabrika GRANT ALL PRIVILEGES ON TABLES TO lafabrika;
ALTER DEFAULT PRIVILEGES IN SCHEMA lafabrika GRANT ALL PRIVILEGES ON SEQUENCES TO lafabrika;
ALTER DEFAULT PRIVILEGES IN SCHEMA lafabrika GRANT ALL PRIVILEGES ON FUNCTIONS TO lafabrika;
ALTER DEFAULT PRIVILEGES IN SCHEMA lafabrika GRANT ALL PRIVILEGES ON TYPES TO lafabrika;

COMMIT;
